# Generated by Django 2.1.2 on 2018-11-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('login_name', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
                ('address_line_1', models.CharField(max_length=150)),
                ('address_line_2', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=3)),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
