# Generated by Django 2.1.2 on 2018-11-28 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0007_auto_20181128_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='login_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='password',
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customers',
            name='telephone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='customers',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
